classifier:

  embeddings:
    embeddings: "bert-base-cased"    # roberta-base or bert-base-cased
    tokenizer: "bert-base-cased"     # roberta-base or bert-base-cased

  model:
  
    epochs: 100
    batch_size: 4
    positive_class_weight: 1
    early_stopping: 10
    random_seed: 0

    destination_path: "results/cola_bert1"                  
    
  interpretation:
    analysis: False   

  data:
    path: "data/cola_public/raw"
    train_file: "in_domain_train.tsv"
    dev_file: "in_domain_dev.tsv"
    test_file: "out_of_domain_dev.tsv"
 
