classifier:

  embeddings:
    embeddings: "prajjwal1/bert-medium"    # roberta-base or bert-base-cased
    tokenizer: "prajjwal1/bert-medium"     # roberta-base or bert-base-cased

  model:
  
    epochs: 100
    batch_size: 4
    positive_class_weight: 1
    early_stopping: 10
    random_seed: 121

    destination_path: "results/cola_medium3"    

  interpretation:
    analysis: False                 
    
  data:
    path: "data/cola_public/raw"
    train_file: "in_domain_train.tsv"
    dev_file: "in_domain_dev.tsv"
    test_file: "out_of_domain_dev.tsv"
 
