classifier:

  embeddings:
    embeddings: "bert-base-cased"    # roberta-base or bert-base-cased
    tokenizer: "bert-base-cased"     # roberta-base or bert-base-cased

  model:
  
    epochs: 100
    batch_size: 4
    positive_class_weight: 1
    early_stopping: 10
    random_seed: 934

    destination_path: "../results/bert4"                  
    
  data:
    path: "../data/hatespeech"
    train_file: "train.csv"
    dev_file: "dev.csv"
    test_file: "test.csv"

 
