classifier:

  embeddings:
    embeddings: "roberta-base"                           # roberta-base or bert-base-cased
    tokenizer: "roberta-base"                            # roberta-base or bert-base-cased

  model:
    epochs: 1
    batch_size: 4
    positive_class_weight: 1
    early_stopping: 10
    random_seed: 42

    destination_path: "../results/cola"                  
    
  data:
    path: "../data/cola_public/raw"
    train_file: "in_domain_dev.tsv"
    dev_file: "in_domain_dev.tsv"
    test_file: "out_of_domain_dev.tsv"

 
