classifier:

  embeddings:
    load_from: "../results/debug2/model_best_acc.pt"
    embeddings: "prajjwal1/bert-medium"                           # roberta-base or bert-base-cased or prajjwal1/bert-medium
    tokenizer: "prajjwal1/bert-medium"                            # roberta-base or bert-base-cased or prajjwal1/bert-medium

  model:
    epochs: 1
    batch_size: 4
    positive_class_weight: 1
    early_stopping: 10
    random_seed: 42

    destination_path: "../results/debug_bert-medium"
    
  data:
    path: "../data/hatespeech"
    train_file: "debug_train.csv"
    dev_file: "debug_dev.csv"
    test_file: "debug_test.csv"

 
