classifier:

  embeddings:
    load_from: "../results/blub_blub/model_best_acc.pt"
    embeddings: "roberta-base"                           # roberta-base or bert-base-cased
    tokenizer: "roberta-base"                            # roberta-base or bert-base-cased

  model:
    epochs: 1
    batch_size: 4
    positive_class_weight: 1
    early_stopping: 10
    random_seed: 42

    destination_path: "../results/blub_blub2"                  
    
  data:
    path: "../data/hatespeech"
    train_file: "debug_train.csv"
    dev_file: "debug_dev.csv"
    test_file: "debug_test.csv"

 
